### PR TITLE
fix: re-detect unknown universe on registry load (#401)

### LINKED ISSUE #401: Registered squads show 'unknown' universe forever — no refresh mechanism
When a squad is registered before universe detection was implemented (or when detection fails at registration time), the universe stays 'unknown' permanently. There's no mechanism to re-detect it later.

**Root cause:** \loadSquads()\ in registry.ts doesn't attempt re-detection for 'unknown' entries. Discovery skips already-registered squads. The only partial fix is \utoRegisterWorkspaceSquads()\ which updates universe on workspace load, but it's not comprehensive.

**Also:** The backward-compat migration for \launchCommand\ → structured fields is in-memory only. Old registry files on disk retain the deprecated \launchCommand\ field indefinitely.

**Proposed fix:**
- Option A: In \loadSquads()\, detect + update universe for 'unknown' entries (reads filesystem, but only for unknowns)
- Option B: Add a one-time migration that writes back to disk after the first load
- Option C: Combine both — migrate on load, persist on save

**Screenshot:** AI Office Squad shows 'unknown' despite having a detectable universe in its team.md/casting directory.

### PR DESCRIPTION
**Pull request by cirvine-MSFT**
Closes #401
Working as Morty (Extension Dev)

## Changes
- Re-detect universe for 'unknown' entries during loadSquads()
- Persist launchCommand migration and universe changes to disk
- Uses parseTeamMd + readUniverseFromRegistry for detection

## Testing
All existing + new tests pass (832 total)

### CODE REVIEW

File: src/registry.ts [hunk 1]
```diff
@@ -21,6 +24,7 @@ export class EditlessRegistry {
         return true;
       });
       // Migrate legacy launchCommand entries to structured fields
+      let needsPersist = false;
```
Comment (cirvine-MSFT) [inline src/registry.ts]: It isn't clear that this variable applies to the universe field. Easy to misunderstand
